# Generated by Django 4.1.3 on 2022-11-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='address',
        ),
    ]
