# Generated by Django 4.1.3 on 2022-11-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_user_role_selections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selections',
            name='items',
        ),
        migrations.AddField(
            model_name='selections',
            name='items',
            field=models.ManyToManyField(null=True, to='ads.ads'),
        ),
    ]
