# Generated by Django 4.1.3 on 2022-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_remove_selections_items_selections_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.SmallIntegerField(null=True, verbose_name='Возраст'),
        ),
    ]
