# Generated by Django 4.1.3 on 2022-11-30 16:04

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_ads_name_alter_ads_price_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.TextField(blank=True, max_length=800, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='is_published',
            field=models.BooleanField(default=True, validators=[ads.models.is_published_not_true], verbose_name='Опубликовано'),
        ),
    ]
