# Generated by Django 4.1.3 on 2022-12-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_user_birth_date_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
